version: "3.8"

services:
  ui:
    build:
      context: .
      target: production
    environment:
      # Set your backend API URL here - this will be injected at runtime
      - VITE_API_BASE_URL=${BACKEND_API_URL:-http://localhost:8000}
    ports:
      - "3000:3000"
