-- This script alters the 'notebooks' table to make several columns nullable,
-- aligning the database schema with the updated SQLAlchemy model.

-- Start a transaction
BEGIN;

-- Remove the NOT NULL constraint from the 'emoji' column
ALTER TABLE notebooks
    ALTER COLUMN emoji DROP NOT NULL;

-- Remove the NOT NULL constraint from the 'title' column
ALTER TABLE notebooks
    ALTER COLUMN title DROP NOT NULL;

-- Remove the NOT NULL constraint from the 'date' column
ALTER TABLE notebooks
    ALTER COLUMN date DROP NOT NULL;

-- Note: The 'created_at' and 'updated_at' columns are often created with
-- a NOT NULL constraint by default in many frameworks. This script ensures
-- they are also nullable, in case they were previously set as NOT NULL.
ALTER TABLE notebooks
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE notebooks
    ALTER COLUMN updated_at DROP NOT NULL;

-- Commit the transaction
COMMIT;




CREATE TABLE propositions (
    -- The primary key, a UUID automatically generated by the database
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The foreign key referencing the 'notebooks' table. It cannot be null.
    notebook_id UUID NOT NULL REFERENCES notebooks(id),

    -- Text fields for the proposition details, which are all optional
    service TEXT,
    audience TEXT,
    problem TEXT,
    solution TEXT,

    -- Timestamps with time zone information
    -- 'created_at' is set once upon row creation
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- 'updated_at' is also set upon creation and will be updated by a trigger
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create an index on the foreign key column for faster lookups.
-- This corresponds to `index=True` in the SQLAlchemy model.
CREATE INDEX idx_propositions_notebook_id ON propositions(notebook_id);

-- This script assumes your foreign key constraint is named 'propositions_notebook_id_fkey'.
-- To find the actual name, connect to your database with psql and run: \d propositions

BEGIN; -- Start a transaction

-- Step 1: Drop the old primary key constraint that was on the 'id' column.
ALTER TABLE propositions DROP CONSTRAINT propositions_pkey;

-- Step 2: Drop the now-redundant 'id' column.
ALTER TABLE propositions DROP COLUMN id;

-- Step 3: Make the 'notebook_id' column the new primary key.
-- This automatically makes it NOT NULL and creates a unique index.
ALTER TABLE propositions ADD PRIMARY KEY (notebook_id);

-- Step 4 (Recommended): Update the Foreign Key to include ON DELETE CASCADE.
-- This ensures that if a notebook is deleted, its corresponding proposition is also deleted.
-- a. First, drop the old foreign key constraint.
ALTER TABLE propositions DROP CONSTRAINT propositions_notebook_id_fkey;

-- b. Then, add it back with the CASCADE rule.
ALTER TABLE propositions
ADD CONSTRAINT propositions_notebook_id_fkey
FOREIGN KEY (notebook_id) REFERENCES notebooks(id) ON DELETE CASCADE;

COMMIT; -- Commit the transaction